<?php


namespace app\common\controller;

use app\BaseController;
use think\facade\Request;
use think\facade\Cookie;
class Frontend extends BaseController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


}